using System;
using System.Collections.Generic;
using UnityEngine;

namespace Aroko.StoreRelease.Editor.Configuration
{
    public enum StorePlatform
    {
        None = 0,
        Steam = 1,
        Epic = 2
    }

    public enum StoreReleaseChannel
    {
        Development = 0,
        Stage = 1,
        Live = 2
    }

    public enum StoreValidationSeverity
    {
        Info = 0,
        Warning = 1,
        Error = 2
    }

    [Serializable]
    public sealed class StoreValidationIssue
    {
        [SerializeField] private StoreValidationSeverity severity;
        [SerializeField] private string code = string.Empty;
        [SerializeField] private string message = string.Empty;
        [SerializeField] private string context = string.Empty;

        public StoreValidationIssue()
        {
        }

        public StoreValidationIssue(
            StoreValidationSeverity severity,
            string code,
            string message,
            string context = "")
        {
            this.severity = severity;
            this.code = code ?? string.Empty;
            this.message = message ?? string.Empty;
            this.context = context ?? string.Empty;
        }

        public StoreValidationSeverity Severity
        {
            get => severity;
            set => severity = value;
        }

        public string Code
        {
            get => code;
            set => code = value ?? string.Empty;
        }

        public string Message
        {
            get => message;
            set => message = value ?? string.Empty;
        }

        public string Context
        {
            get => context;
            set => context = value ?? string.Empty;
        }

        public override string ToString()
        {
            return string.IsNullOrWhiteSpace(context)
                ? $"[{severity}] {code}: {message}"
                : $"[{severity}] {code}: {message} ({context})";
        }
    }

    [Serializable]
    public sealed class EpicEnvironmentDefinition
    {
        [SerializeField, Tooltip("Unique label referenced by Epic build profiles.")]
        private string name = string.Empty;
        [SerializeField, Tooltip("Development, Stage, or Live release environment.")]
        private StoreReleaseChannel channel;
        [SerializeField, Tooltip("Epic product ID used by the packaged EOS configuration.")]
        private string productId = string.Empty;
        [SerializeField, Tooltip("EOS sandbox ID for this release environment.")]
        private string sandboxId = string.Empty;
        [SerializeField, Tooltip("EOS deployment ID matched to the sandbox.")]
        private string deploymentId = string.Empty;
        [SerializeField, Tooltip("Public EOS runtime Client ID.")]
        private string eosClientId = string.Empty;
        [SerializeField, Tooltip("EOS launcher client configuration included in the Epic build.")]
        private string clientSecret = string.Empty;
        [SerializeField, Tooltip("Stable EOS artifact encryption key generated by the toolkit.")]
        private string encryptionKey = string.Empty;
        [SerializeField, Tooltip("Additional arguments passed through the Epic launcher bootstrapper.")]
        private string appArgs = string.Empty;
        [SerializeField, Tooltip("Include and validate the Epic launcher bootstrapper.")]
        private bool useBootstrapper = true;

        public string Name
        {
            get => name;
            set => name = value ?? string.Empty;
        }

        public StoreReleaseChannel Channel
        {
            get => channel;
            set => channel = value;
        }

        public string ProductId
        {
            get => productId;
            set => productId = value ?? string.Empty;
        }

        public string SandboxId
        {
            get => sandboxId;
            set => sandboxId = value ?? string.Empty;
        }

        public string DeploymentId
        {
            get => deploymentId;
            set => deploymentId = value ?? string.Empty;
        }

        public string EosClientId
        {
            get => eosClientId;
            set => eosClientId = value ?? string.Empty;
        }

        public string ClientSecret
        {
            get => clientSecret;
            set => clientSecret = value ?? string.Empty;
        }

        public string EncryptionKey
        {
            get => encryptionKey;
            set => encryptionKey = value ?? string.Empty;
        }

        public string AppArgs
        {
            get => appArgs;
            set => appArgs = value ?? string.Empty;
        }

        public bool UseBootstrapper
        {
            get => useBootstrapper;
            set => useBootstrapper = value;
        }

    }

    [Serializable]
    public sealed class StoreBuildProfile
    {
        [SerializeField, Tooltip("Stable unique profile ID used by CLI and transaction state.")]
        private string id = string.Empty;
        [SerializeField, Tooltip("Human-readable profile name shown in the dashboard.")]
        private string displayName = string.Empty;
        [SerializeField, Tooltip("Steam or Epic build target.")]
        private StorePlatform store;
        [SerializeField, Tooltip("Development, Stage, or Live release channel.")]
        private StoreReleaseChannel channel;
        [SerializeField, Tooltip("Enable Unity development-build diagnostics for this profile.")]
        private bool developmentBuild;
        [SerializeField, Tooltip("Output path supporting {Store}, {Profile}, and {Version} tokens.")]
        private string outputTemplate =
            "Builds/StoreReleaseToolkit/{Store}/{Profile}/{Version}";
        [SerializeField, Tooltip("Epic environment label used to package EOS configuration.")]
        private string epicEnvironmentName = string.Empty;

        public string Id
        {
            get => id;
            set => id = value ?? string.Empty;
        }

        public string DisplayName
        {
            get => displayName;
            set => displayName = value ?? string.Empty;
        }

        public StorePlatform Store
        {
            get => store;
            set => store = value;
        }

        public StoreReleaseChannel Channel
        {
            get => channel;
            set => channel = value;
        }

        public bool DevelopmentBuild
        {
            get => developmentBuild;
            set => developmentBuild = value;
        }

        public string OutputTemplate
        {
            get => outputTemplate;
            set => outputTemplate = value ?? string.Empty;
        }

        public string EpicEnvironmentName
        {
            get => epicEnvironmentName;
            set => epicEnvironmentName = value ?? string.Empty;
        }

        public StoreBuildProfile Clone()
        {
            return JsonUtility.FromJson<StoreBuildProfile>(JsonUtility.ToJson(this));
        }
    }

    [Serializable]
    public sealed class StoreBuildRequest
    {
        [SerializeField] private StoreBuildProfile profile;
        [SerializeField] private string version = string.Empty;
        [SerializeField] private string outputPath = string.Empty;

        public StoreBuildRequest()
        {
        }

        public StoreBuildRequest(
            StoreBuildProfile profile,
            string version,
            string outputPath)
        {
            this.profile = profile;
            this.version = version ?? string.Empty;
            this.outputPath = outputPath ?? string.Empty;
        }

        public StoreBuildProfile Profile
        {
            get => profile;
            set => profile = value;
        }

        public string Version
        {
            get => version;
            set => version = value ?? string.Empty;
        }

        public string OutputPath
        {
            get => outputPath;
            set => outputPath = value ?? string.Empty;
        }

    }

    [Serializable]
    public sealed class StoreOperationReport
    {
        [SerializeField] private bool succeeded;
        [SerializeField] private List<StoreValidationIssue> issues = new List<StoreValidationIssue>();
        [SerializeField] private string outputPath = string.Empty;
        [SerializeField] private string logPath = string.Empty;

        public bool Succeeded
        {
            get => succeeded;
            set => succeeded = value;
        }

        public List<StoreValidationIssue> Issues
        {
            get
            {
                if (issues == null)
                {
                    issues = new List<StoreValidationIssue>();
                }

                return issues;
            }
            set => issues = value ?? new List<StoreValidationIssue>();
        }

        public string OutputPath
        {
            get => outputPath;
            set => outputPath = value ?? string.Empty;
        }

        public string LogPath
        {
            get => logPath;
            set => logPath = value ?? string.Empty;
        }

        public void AddIssue(StoreValidationIssue issue)
        {
            if (issue == null)
            {
                return;
            }

            Issues.Add(issue);
            if (issue.Severity == StoreValidationSeverity.Error)
            {
                succeeded = false;
            }
        }

        public static StoreOperationReport Success(string outputPath = "", string logPath = "")
        {
            return new StoreOperationReport
            {
                Succeeded = true,
                OutputPath = outputPath,
                LogPath = logPath
            };
        }

        public static StoreOperationReport Failure(string code, string message)
        {
            var report = new StoreOperationReport { Succeeded = false };
            report.AddIssue(new StoreValidationIssue(StoreValidationSeverity.Error, code, message));
            return report;
        }
    }
}
